# Generated by Django 3.2.6 on 2021-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Handicrafts'), ('A', 'Arts'), ('C', 'Clothes'), ('O', 'Ornaments'), ('S', 'Spices')], max_length=2),
        ),
    ]
