# Generated by Django 3.2.6 on 2021-09-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sellercom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
